# Generated by Django 4.2.24 on 2025-09-10 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPropietarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_cambio', models.DateField()),
                ('motivo', models.CharField(choices=[('venta', 'Venta'), ('herencia', 'Herencia'), ('donacion', 'Donación'), ('permuta', 'Permuta'), ('otro', 'Otro')], max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('documento_soporte', models.FileField(blank=True, null=True, upload_to='propiedades/historiales/')),
            ],
            options={
                'verbose_name': 'Historial de Propietarios',
                'verbose_name_plural': 'Historiales de Propietarios',
                'db_table': 'historial_propietarios',
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('porcentaje_propiedad', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('documento_propiedad', models.FileField(blank=True, null=True, upload_to='propiedades/documentos/')),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
                'db_table': 'propietarios',
            },
        ),
        migrations.CreateModel(
            name='UnidadHabitacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=10)),
                ('piso', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('departamento', 'Departamento'), ('casa', 'Casa'), ('oficina', 'Oficina'), ('local_comercial', 'Local Comercial')], default='departamento', max_length=50)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('num_habitaciones', models.PositiveIntegerField(blank=True, null=True)),
                ('num_banos', models.PositiveIntegerField(blank=True, null=True)),
                ('tiene_balcon', models.BooleanField(default=False)),
                ('tiene_parqueadero', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='core.bloque')),
            ],
            options={
                'verbose_name': 'Unidad Habitacional',
                'verbose_name_plural': 'Unidades Habitacionales',
                'db_table': 'unidades_habitacionales',
            },
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relacion', models.CharField(choices=[('propietario', 'Propietario'), ('arrendatario', 'Arrendatario'), ('familiar', 'Familiar'), ('empleado_domestico', 'Empleado Doméstico'), ('otro', 'Otro')], max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residentes', to='properties.unidadhabitacional')),
            ],
            options={
                'verbose_name': 'Residente',
                'verbose_name_plural': 'Residentes',
                'db_table': 'residentes',
            },
        ),
    ]
