# Generated by Django 4.2.24 on 2025-09-10 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residencias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propietario',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietarios', to='properties.unidadhabitacional'),
        ),
        migrations.AddField(
            model_name='propietario',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialpropietarios',
            name='propietario_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_ventas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialpropietarios',
            name='propietario_nuevo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_compras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialpropietarios',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_propietarios', to='properties.unidadhabitacional'),
        ),
        migrations.AlterUniqueTogether(
            name='unidadhabitacional',
            unique_together={('bloque', 'numero')},
        ),
    ]
