# Generated by Django 4.2.24 on 2025-09-21 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadhabitacional',
            name='piso',
        ),
        migrations.RemoveField(
            model_name='unidadhabitacional',
            name='tiene_balcon',
        ),
        migrations.RemoveField(
            model_name='unidadhabitacional',
            name='tipo',
        ),
    ]
