# Generated by Django 4.2.24 on 2025-09-10 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoComunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('tipo', models.CharField(choices=[('aviso', 'Aviso'), ('comunicado', 'Comunicado'), ('noticia', 'Noticia'), ('urgente', 'Urgente'), ('mantenimiento', 'Mantenimiento')], max_length=50)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('fecha_publicacion', models.DateTimeField()),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='avisos/adjuntos/')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avisos/imagenes/')),
            ],
            options={
                'verbose_name': 'Aviso/Comunicado',
                'verbose_name_plural': 'Avisos/Comunicados',
                'db_table': 'avisos_comunicados',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='LecturaAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_lectura', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='communications.avisocomunicado')),
            ],
            options={
                'verbose_name': 'Lectura de Aviso',
                'verbose_name_plural': 'Lecturas de Avisos',
                'db_table': 'lectura_avisos',
            },
        ),
    ]
