# Generated by Django 4.2.24 on 2025-09-10 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communications', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturaaviso',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_leidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avisocomunicado',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avisocomunicado',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='core.condominio'),
        ),
        migrations.AlterUniqueTogether(
            name='lecturaaviso',
            unique_together={('aviso', 'user')},
        ),
    ]
