# Generated by Django 4.2.24 on 2025-09-26 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculos',
            },
        ),
        migrations.CreateModel(
            name='VehicleAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placa_detectada', models.CharField(max_length=20)),
                ('confianza_ocr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resultado', models.CharField(choices=[('autorizado', 'Autorizado'), ('denegado', 'Denegado'), ('desconocido', 'Desconocido')], max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('timestamp_evento', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='ai_security.vehicle')),
            ],
            options={
                'verbose_name': 'Log de Acceso Vehicular',
                'verbose_name_plural': 'Logs de Acceso Vehicular',
                'db_table': 'vehicle_access_logs',
                'ordering': ['-timestamp_evento'],
            },
        ),
    ]
