# Generated by Django 4.2.24 on 2026-02-20 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=20)),
                ('video_name', models.CharField(max_length=255)),
                ('video_url', models.URLField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('job_id', models.CharField(blank=True, help_text='ID del job en Rekognition', max_length=255)),
                ('iniciado_at', models.DateTimeField(auto_now_add=True)),
                ('completado_at', models.DateTimeField(blank=True, null=True)),
                ('actividades_detectadas', models.IntegerField(default=0)),
                ('confianza_promedio', models.FloatField(blank=True, null=True)),
                ('error_mensaje', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis de Video',
                'verbose_name_plural': 'Análisis de Videos',
                'db_table': 'analisis_videos',
                'ordering': ['-iniciado_at'],
            },
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(choices=[('SOSPECHOSA', 'Actividad Sospechosa'), ('ACCIDENTE', 'Accidente Vehicular'), ('ANIMAL', 'Animal Suelto')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('palabras_clave', models.TextField(help_text='Palabras clave separadas por comas para detección en Rekognition')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Actividad',
                'verbose_name_plural': 'Tipos de Actividad',
                'db_table': 'tipos_actividad',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculos',
            },
        ),
        migrations.CreateModel(
            name='VehicleAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placa_detectada', models.CharField(blank=True, default='', max_length=20)),
                ('confianza_ocr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resultado', models.CharField(choices=[('autorizado', 'Autorizado'), ('denegado', 'Denegado'), ('desconocido', 'Desconocido')], max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('timestamp_evento', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='ai_security.vehicle')),
            ],
            options={
                'verbose_name': 'Log de Acceso Vehicular',
                'verbose_name_plural': 'Logs de Acceso Vehicular',
                'db_table': 'vehicle_access_logs',
                'ordering': ['-timestamp_evento'],
            },
        ),
        migrations.CreateModel(
            name='VehicleOCRTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placa_detectada_original', models.CharField(blank=True, help_text='Placa que detectó el OCR originalmente', max_length=20)),
                ('placa_correcta', models.CharField(help_text='Placa correcta según corrección manual', max_length=20)),
                ('extracted_text_original', models.TextField(blank=True, help_text='Texto extraído por OCR')),
                ('confianza_original', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('access_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_data', to='ai_security.vehicleaccesslog')),
                ('usuario_correccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dato de Entrenamiento OCR',
                'verbose_name_plural': 'Datos de Entrenamiento OCR',
                'db_table': 'vehicle_ocr_training_data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('person_type', models.CharField(choices=[('resident', 'Residente'), ('visitor', 'Visitante'), ('employee', 'Empleado'), ('delivery', 'Delivery'), ('unknown', 'Desconocido')], max_length=20)),
                ('face_encoding', models.TextField(blank=True, help_text='JSON con encoding facial', null=True)),
                ('aws_face_id', models.CharField(blank=True, help_text='AWS Rekognition Face ID', max_length=100, null=True)),
                ('photo', models.ImageField(upload_to='faces/')),
                ('is_authorized', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Persona',
                'verbose_name_plural': 'Perfiles de Personas',
                'db_table': 'person_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacialAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='access_logs/')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('access_granted', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, default='Entrada Principal', max_length=100)),
                ('timestamp_evento', models.DateTimeField(auto_now_add=True)),
                ('detected_name', models.CharField(blank=True, help_text='Nombre detectado por el sistema', max_length=100)),
                ('person_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='ai_security.personprofile')),
            ],
            options={
                'verbose_name': 'Log de Acceso Facial',
                'verbose_name_plural': 'Logs de Acceso Facial',
                'db_table': 'facial_access_logs',
                'ordering': ['-timestamp_evento'],
            },
        ),
        migrations.CreateModel(
            name='DeteccionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_inicio', models.FloatField(help_text='Segundo del video donde inicia la actividad')),
                ('timestamp_fin', models.FloatField(help_text='Segundo del video donde termina la actividad')),
                ('confianza', models.FloatField(help_text='Nivel de confianza de 0 a 100')),
                ('objetos_detectados', models.JSONField(default=list, help_text='Lista de objetos detectados')),
                ('bounding_boxes', models.JSONField(default=list, help_text='Coordenadas de los objetos')),
                ('aviso_generado', models.BooleanField(default=False)),
                ('aviso_id', models.IntegerField(blank=True, help_text='ID del aviso generado', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detecciones', to='ai_security.analisisvideo')),
                ('tipo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_security.tipoactividad')),
            ],
            options={
                'verbose_name': 'Detección de Actividad',
                'verbose_name_plural': 'Detecciones de Actividad',
                'db_table': 'detecciones_actividad',
                'ordering': ['-created_at'],
            },
        ),
    ]
