# Generated by Django 4.2.24 on 2025-09-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleaccesslog',
            name='placa_detectada',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
