# Generated by Django 4.2.24 on 2025-09-27 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_security', '0002_alter_vehicleaccesslog_placa_detectada'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleOCRTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placa_detectada_original', models.CharField(blank=True, help_text='Placa que detectó el OCR originalmente', max_length=20)),
                ('placa_correcta', models.CharField(help_text='Placa correcta según corrección manual', max_length=20)),
                ('extracted_text_original', models.TextField(blank=True, help_text='Texto extraído por OCR')),
                ('confianza_original', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('access_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_data', to='ai_security.vehicleaccesslog')),
                ('usuario_correccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dato de Entrenamiento OCR',
                'verbose_name_plural': 'Datos de Entrenamiento OCR',
                'db_table': 'vehicle_ocr_training_data',
                'ordering': ['-created_at'],
            },
        ),
    ]
