# Generated by Django 4.2.24 on 2025-09-27 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_security', '0003_vehicleocrtrainingdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('person_type', models.CharField(choices=[('resident', 'Residente'), ('visitor', 'Visitante'), ('employee', 'Empleado'), ('delivery', 'Delivery'), ('unknown', 'Desconocido')], max_length=20)),
                ('face_encoding', models.TextField(help_text='JSON con encoding facial')),
                ('photo', models.ImageField(upload_to='faces/')),
                ('is_authorized', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Persona',
                'verbose_name_plural': 'Perfiles de Personas',
                'db_table': 'person_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacialAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='access_logs/')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('access_granted', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, default='Entrada Principal', max_length=100)),
                ('timestamp_evento', models.DateTimeField(auto_now_add=True)),
                ('detected_name', models.CharField(blank=True, help_text='Nombre detectado por el sistema', max_length=100)),
                ('person_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='ai_security.personprofile')),
            ],
            options={
                'verbose_name': 'Log de Acceso Facial',
                'verbose_name_plural': 'Logs de Acceso Facial',
                'db_table': 'facial_access_logs',
                'ordering': ['-timestamp_evento'],
            },
        ),
    ]
