# Generated by Django 4.2.24 on 2025-09-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_security', '0004_personprofile_facialaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='personprofile',
            name='aws_face_id',
            field=models.CharField(blank=True, help_text='AWS Rekognition Face ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='face_encoding',
            field=models.TextField(blank=True, help_text='JSON con encoding facial', null=True),
        ),
    ]
