# Generated by Django 4.2.24 on 2025-09-29 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_security', '0005_personprofile_aws_face_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=20)),
                ('video_name', models.CharField(max_length=255)),
                ('video_url', models.URLField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('job_id', models.CharField(blank=True, help_text='ID del job en Rekognition', max_length=255)),
                ('iniciado_at', models.DateTimeField(auto_now_add=True)),
                ('completado_at', models.DateTimeField(blank=True, null=True)),
                ('actividades_detectadas', models.IntegerField(default=0)),
                ('confianza_promedio', models.FloatField(blank=True, null=True)),
                ('error_mensaje', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis de Video',
                'verbose_name_plural': 'Análisis de Videos',
                'db_table': 'analisis_videos',
                'ordering': ['-iniciado_at'],
            },
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(choices=[('SOSPECHOSA', 'Actividad Sospechosa'), ('ACCIDENTE', 'Accidente Vehicular'), ('ANIMAL', 'Animal Suelto')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('palabras_clave', models.TextField(help_text='Palabras clave separadas por comas para detección en Rekognition')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Actividad',
                'verbose_name_plural': 'Tipos de Actividad',
                'db_table': 'tipos_actividad',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='DeteccionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_inicio', models.FloatField(help_text='Segundo del video donde inicia la actividad')),
                ('timestamp_fin', models.FloatField(help_text='Segundo del video donde termina la actividad')),
                ('confianza', models.FloatField(help_text='Nivel de confianza de 0 a 100')),
                ('objetos_detectados', models.JSONField(default=list, help_text='Lista de objetos detectados')),
                ('bounding_boxes', models.JSONField(default=list, help_text='Coordenadas de los objetos')),
                ('aviso_generado', models.BooleanField(default=False)),
                ('aviso_id', models.IntegerField(blank=True, help_text='ID del aviso generado', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detecciones', to='ai_security.analisisvideo')),
                ('tipo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_security.tipoactividad')),
            ],
            options={
                'verbose_name': 'Detección de Actividad',
                'verbose_name_plural': 'Detecciones de Actividad',
                'db_table': 'detecciones_actividad',
                'ordering': ['-created_at'],
            },
        ),
    ]
