# Generated by Django 4.2.24 on 2025-09-21 19:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_remove_unidadhabitacional_piso_and_more'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.TextField(help_text='Nombre del área común')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('mantenimiento', 'En Mantenimiento'), ('fuera_de_servicio', 'Fuera de Servicio'), ('reservado', 'Reservado')], default='disponible', help_text='Estado actual del área común', max_length=20)),
                ('precio_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio base por hora/uso del área', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('moneda', models.CharField(default='B', help_text='Moneda del precio (B=Bolivianos, D=Dólares)', max_length=1)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del área común')),
                ('capacidad_maxima', models.PositiveIntegerField(default=1, help_text='Capacidad máxima de personas')),
                ('horario_apertura', models.TimeField(default='06:00:00', help_text='Horario de apertura')),
                ('horario_cierre', models.TimeField(default='22:00:00', help_text='Horario de cierre')),
                ('requiere_aprobacion', models.BooleanField(default=False, help_text='Si requiere aprobación del administrador')),
                ('tiempo_maximo_reserva', models.PositiveIntegerField(default=4, help_text='Tiempo máximo de reserva en horas')),
                ('imagen_url', models.URLField(blank=True, help_text='URL de imagen del área común', null=True)),
            ],
            options={
                'verbose_name': 'Área Común',
                'verbose_name_plural': 'Áreas Comunes',
                'db_table': 'areas_comunes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReservaArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha y hora de inicio de la reserva')),
                ('fecha_fin', models.DateTimeField(help_text='Fecha y hora de fin de la reserva')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_uso', 'En Uso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendiente', help_text='Estado actual de la reserva', max_length=15)),
                ('precio_total', models.DecimalField(decimal_places=2, help_text='Precio total de la reserva', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('moneda', models.CharField(default='B', help_text='Moneda del precio', max_length=1)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales de la reserva')),
                ('numero_personas', models.PositiveIntegerField(default=1, help_text='Número de personas para la reserva')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('area', models.ForeignKey(db_column='id_area', help_text='Área común reservada', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='areas_comunes.areacomun')),
                ('cargo', models.ForeignKey(blank=True, db_column='id_cargo', help_text='Cargo financiero asociado (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_area', to='finances.cargo')),
                ('propietario', models.ForeignKey(db_column='id_propietario', help_text='Propietario que realiza la reserva', on_delete=django.db.models.deletion.CASCADE, related_name='reservas_areas', to='properties.propietario')),
            ],
            options={
                'verbose_name': 'Reserva de Área',
                'verbose_name_plural': 'Reservas de Áreas',
                'db_table': 'reservas_area',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
