# Generated by Django 4.2.24 on 2025-09-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas_comunes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areacomun',
            name='capacidad_maxima',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='horario_apertura',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='horario_cierre',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='imagen_url',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='requiere_aprobacion',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='tiempo_maximo_reserva',
        ),
        migrations.AlterField(
            model_name='areacomun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_creacion'),
        ),
        migrations.AlterField(
            model_name='areacomun',
            name='moneda',
            field=models.CharField(default='BOB', help_text='Moneda del precio (BOB=Bolivianos, USD=Dólares)', max_length=3),
        ),
        migrations.AlterField(
            model_name='areacomun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='fecha_actualizacion'),
        ),
        migrations.AlterField(
            model_name='reservaarea',
            name='moneda',
            field=models.CharField(default='BOB', help_text='Moneda del precio', max_length=3),
        ),
    ]
