# Generated by Django 4.2.24 on 2026-02-20 01:14

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInfraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(help_text="Código único para el tipo de infracción (ej: 'ruido_excesivo')", max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del tipo de infracción', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del tipo de infracción')),
                ('monto_base', models.DecimalField(decimal_places=2, help_text='Monto base para primera infracción', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('monto_reincidencia', models.DecimalField(decimal_places=2, help_text='Monto para casos de reincidencia', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('dias_para_pago', models.PositiveIntegerField(default=15, help_text='Días para pagar la multa desde su aplicación')),
                ('es_activo', models.BooleanField(default=True, help_text='Si este tipo de infracción está activo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Tipo de Infracción',
                'verbose_name_plural': 'Tipos de Infracción',
                'db_table': 'tipos_infraccion',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Infraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Descripción detallada de la infracción')),
                ('fecha_infraccion', models.DateTimeField(help_text='Fecha y hora cuando ocurrió la infracción')),
                ('evidencia_url', models.URLField(blank=True, help_text='URL de evidencia (fotos, videos, documentos)', null=True)),
                ('monto_multa', models.DecimalField(blank=True, decimal_places=2, help_text='Monto de la multa aplicada (si corresponde)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fecha_limite_pago', models.DateField(blank=True, help_text='Fecha límite para pagar la multa', null=True)),
                ('estado', models.CharField(choices=[('registrada', 'Registrada'), ('en_revision', 'En Revisión'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada'), ('multa_aplicada', 'Multa Aplicada'), ('pagada', 'Pagada')], default='registrada', help_text='Estado actual de la infracción', max_length=20)),
                ('observaciones_admin', models.TextField(blank=True, help_text='Observaciones del administrador')),
                ('es_reincidente', models.BooleanField(default=False, help_text='Si el propietario es reincidente en este tipo de infracción')),
                ('monto_calculado', models.DecimalField(blank=True, decimal_places=2, help_text='Monto calculado automáticamente según el tipo de infracción y reincidencia', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('propietario', models.ForeignKey(db_column='id_propietario', help_text='Propietario responsable de la infracción', on_delete=django.db.models.deletion.CASCADE, related_name='infracciones', to='properties.propietario')),
                ('reportado_por', models.ForeignKey(blank=True, db_column='reportado_por', help_text='Usuario que reportó la infracción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infracciones_reportadas', to=settings.AUTH_USER_MODEL)),
                ('tipo_infraccion', models.ForeignKey(help_text='Tipo de infracción', on_delete=django.db.models.deletion.CASCADE, related_name='infracciones', to='finances.tipoinfraccion')),
                ('unidad', models.ForeignKey(db_column='unidad', help_text='Unidad habitacional donde ocurrió la infracción', on_delete=django.db.models.deletion.CASCADE, related_name='infracciones', to='properties.unidadhabitacional')),
            ],
            options={
                'verbose_name': 'Infracción',
                'verbose_name_plural': 'Infracciones',
                'db_table': 'infracciones',
                'ordering': ['-fecha_infraccion'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('concepto', models.TextField(help_text='Descripción del concepto del cargo')),
                ('tipo_cargo', models.CharField(choices=[('cuota_mensual', 'Cuota Mensual'), ('expensa_extraordinaria', 'Expensa Extraordinaria'), ('multa', 'Multa'), ('interes_mora', 'Interés por Mora'), ('otros', 'Otros')], default='cuota_mensual', help_text='Tipo específico de cargo', max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del cargo', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('moneda', models.CharField(default='BOB', help_text='Moneda del cargo (BOB, USD, etc.)', max_length=3)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, help_text='Fecha de emisión del cargo')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha límite de pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcialmente_pagado', 'Parcialmente Pagado'), ('pagado', 'Pagado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado'), ('en_revision', 'En Revisión')], default='pendiente', help_text='Estado actual del cargo', max_length=20)),
                ('es_recurrente', models.BooleanField(default=False, help_text='Si es un cargo que se repite mensualmente')),
                ('periodo', models.CharField(blank=True, help_text="Período al que corresponde (ej: 'Enero 2024')", max_length=20)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto total pagado', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tasa_interes_mora', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Tasa de interés por mora (% mensual)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('infraccion', models.ForeignKey(blank=True, help_text='Infracción que generó este cargo (si es una multa)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargos_multa', to='finances.infraccion')),
                ('propietario', models.ForeignKey(db_column='id_propietario', help_text='Propietario al que se le aplica el cargo', on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='properties.propietario')),
                ('unidad', models.ForeignKey(db_column='unidad_id', help_text='Unidad habitacional asociada al cargo', on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='properties.unidadhabitacional')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargos',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
