# Generated by Django 4.2.24 on 2025-09-21 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0003_remove_unidadhabitacional_piso_and_more'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraccion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_creacion'),
        ),
        migrations.AlterField(
            model_name='infraccion',
            name='propietario',
            field=models.ForeignKey(db_column='id_propietario', help_text='Propietario responsable de la infracción', on_delete=django.db.models.deletion.CASCADE, related_name='infracciones', to='properties.propietario'),
        ),
        migrations.AlterField(
            model_name='infraccion',
            name='reportado_por',
            field=models.ForeignKey(blank=True, db_column='reportado_por', help_text='Usuario que reportó la infracción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infracciones_reportadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='infraccion',
            name='unidad',
            field=models.ForeignKey(db_column='unidad', help_text='Unidad habitacional donde ocurrió la infracción', on_delete=django.db.models.deletion.CASCADE, related_name='infracciones', to='properties.unidadhabitacional'),
        ),
        migrations.AlterField(
            model_name='infraccion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='fecha_actualizacion'),
        ),
    ]
