# Generated by Django 4.2.24 on 2025-09-27 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_fix_schema_finances'),
    ]

    operations = [
        # Actualizar el constraint de tipo_cargo para permitir los nuevos valores
        migrations.RunSQL(
            """
            -- Eliminar el constraint existente
            ALTER TABLE cargos DROP CONSTRAINT IF EXISTS cargos_tipo_cargo_check;

            -- Crear el nuevo constraint con los valores correctos
            ALTER TABLE cargos ADD CONSTRAINT cargos_tipo_cargo_check
                CHECK (tipo_cargo IN (
                    'cuota_mensual',
                    'expensa_extraordinaria',
                    'multa',
                    'interes_mora',
                    'otros',
                    'mantenimiento',
                    'extraordinario',
                    'servicio'
                ));
            """,
            reverse_sql="""
            -- Revertir al constraint original
            ALTER TABLE cargos DROP CONSTRAINT IF EXISTS cargos_tipo_cargo_check;
            ALTER TABLE cargos ADD CONSTRAINT cargos_tipo_cargo_check
                CHECK (tipo_cargo IN ('mantenimiento', 'extraordinario', 'servicio'));
            """
        ),

        # También actualizar el constraint de estado si existe
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                -- Verificar si existe el constraint de estado y actualizarlo
                IF EXISTS (SELECT 1 FROM information_schema.check_constraints
                          WHERE constraint_name = 'cargos_estado_check') THEN
                    ALTER TABLE cargos DROP CONSTRAINT cargos_estado_check;
                    ALTER TABLE cargos ADD CONSTRAINT cargos_estado_check
                        CHECK (estado IN (
                            'pendiente',
                            'parcialmente_pagado',
                            'pagado',
                            'vencido',
                            'cancelado'
                        ));
                END IF;
            END $$;
            """,
            reverse_sql=""
        ),
    ]
