# Generated by Django 4.2.24 on 2025-09-27 23:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_unidadhabitacional_piso_and_more'),
        ('finances', '0006_populate_tipo_infraccion_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInfraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(help_text="Código único para el tipo de infracción (ej: 'ruido_excesivo')", max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del tipo de infracción', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del tipo de infracción')),
                ('monto_base', models.DecimalField(decimal_places=2, help_text='Monto base para primera infracción', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('monto_reincidencia', models.DecimalField(decimal_places=2, help_text='Monto para casos de reincidencia', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('dias_para_pago', models.PositiveIntegerField(default=15, help_text='Días para pagar la multa desde su aplicación')),
                ('es_activo', models.BooleanField(default=True, help_text='Si este tipo de infracción está activo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Tipo de Infracción',
                'verbose_name_plural': 'Tipos de Infracción',
                'db_table': 'tipos_infraccion',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.DeleteModel(
            name='ConfiguracionMultas',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_creacion'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='propietario',
            field=models.ForeignKey(db_column='id_propietario', help_text='Propietario al que se le aplica el cargo', on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='properties.propietario'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='unidad',
            field=models.ForeignKey(db_column='unidad_id', help_text='Unidad habitacional asociada al cargo', on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='properties.unidadhabitacional'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='fecha_actualizacion'),
        ),
        migrations.AlterField(
            model_name='infraccion',
            name='tipo_infraccion',
            field=models.CharField(help_text='Tipo de infracción (temporal para migración)', max_length=50),
        ),
        migrations.AddField(
            model_name='infraccion',
            name='tipo_infraccion_fk',
            field=models.ForeignKey(blank=True, help_text='Nuevo campo FK a TipoInfraccion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infracciones', to='finances.tipoinfraccion'),
        ),
    ]
